---
- name: install base packages
  apt:
    name:
      - ca-certificates
      - unzip
      - jq
      - dstat
      - htop
      - iotop
      - ncdu
      - sysstat
      - zip
    update_cache: true
    state: present
